version: "3.8"
services:
  db:
    image: postgres:15
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.example
  back:
    env_file:
      - ./backend/.env.example
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend/node_modules:/app/node_modules
      - ./backend:/app
    expose:
      - 4000
    ports:
      - 4000:4000
